FROM python:2.7
RUN pip install --upgrade pip && \   
    pip install numpy && \ 
    #pip install --no-deps astropy && \
    pip install matplotlib

#RUN apt-get update  && \
    #apt-get install -y vim

